/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MyTicketsRouteImport } from './routes/my-tickets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExportRouteImport } from './routes/export'
import { Route as EmailsRouteImport } from './routes/emails'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as VolunteerTokenRouteImport } from './routes/volunteer.$token'
import { Route as EventsNewRouteImport } from './routes/events.new'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as EventsEventIdEditRouteImport } from './routes/events.$eventId_.edit'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTicketsRoute = MyTicketsRouteImport.update({
  id: '/my-tickets',
  path: '/my-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsRoute = EmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerTokenRoute = VolunteerTokenRouteImport.update({
  id: '/volunteer/$token',
  path: '/volunteer/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdEditRoute = EventsEventIdEditRouteImport.update({
  id: '/events/$eventId_/edit',
  path: '/events/$eventId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/emails': typeof EmailsRoute
  '/export': typeof ExportRoute
  '/login': typeof LoginRoute
  '/my-tickets': typeof MyTicketsRoute
  '/register': typeof RegisterRoute
  '/scanner': typeof ScannerRoute
  '/waitlist': typeof WaitlistRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/new': typeof EventsNewRoute
  '/volunteer/$token': typeof VolunteerTokenRoute
  '/events/': typeof EventsIndexRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/emails': typeof EmailsRoute
  '/export': typeof ExportRoute
  '/login': typeof LoginRoute
  '/my-tickets': typeof MyTicketsRoute
  '/register': typeof RegisterRoute
  '/scanner': typeof ScannerRoute
  '/waitlist': typeof WaitlistRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/new': typeof EventsNewRoute
  '/volunteer/$token': typeof VolunteerTokenRoute
  '/events': typeof EventsIndexRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/emails': typeof EmailsRoute
  '/export': typeof ExportRoute
  '/login': typeof LoginRoute
  '/my-tickets': typeof MyTicketsRoute
  '/register': typeof RegisterRoute
  '/scanner': typeof ScannerRoute
  '/waitlist': typeof WaitlistRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/new': typeof EventsNewRoute
  '/volunteer/$token': typeof VolunteerTokenRoute
  '/events/': typeof EventsIndexRoute
  '/events/$eventId_/edit': typeof EventsEventIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/emails'
    | '/export'
    | '/login'
    | '/my-tickets'
    | '/register'
    | '/scanner'
    | '/waitlist'
    | '/events/$eventId'
    | '/events/new'
    | '/volunteer/$token'
    | '/events/'
    | '/events/$eventId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/emails'
    | '/export'
    | '/login'
    | '/my-tickets'
    | '/register'
    | '/scanner'
    | '/waitlist'
    | '/events/$eventId'
    | '/events/new'
    | '/volunteer/$token'
    | '/events'
    | '/events/$eventId/edit'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/emails'
    | '/export'
    | '/login'
    | '/my-tickets'
    | '/register'
    | '/scanner'
    | '/waitlist'
    | '/events/$eventId'
    | '/events/new'
    | '/volunteer/$token'
    | '/events/'
    | '/events/$eventId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  EmailsRoute: typeof EmailsRoute
  ExportRoute: typeof ExportRoute
  LoginRoute: typeof LoginRoute
  MyTicketsRoute: typeof MyTicketsRoute
  RegisterRoute: typeof RegisterRoute
  ScannerRoute: typeof ScannerRoute
  WaitlistRoute: typeof WaitlistRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  EventsNewRoute: typeof EventsNewRoute
  VolunteerTokenRoute: typeof VolunteerTokenRoute
  EventsIndexRoute: typeof EventsIndexRoute
  EventsEventIdEditRoute: typeof EventsEventIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tickets': {
      id: '/my-tickets'
      path: '/my-tickets'
      fullPath: '/my-tickets'
      preLoaderRoute: typeof MyTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails': {
      id: '/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof EmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/$token': {
      id: '/volunteer/$token'
      path: '/volunteer/$token'
      fullPath: '/volunteer/$token'
      preLoaderRoute: typeof VolunteerTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/new': {
      id: '/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId_/edit': {
      id: '/events/$eventId_/edit'
      path: '/events/$eventId/edit'
      fullPath: '/events/$eventId/edit'
      preLoaderRoute: typeof EventsEventIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRoute,
  EmailsRoute: EmailsRoute,
  ExportRoute: ExportRoute,
  LoginRoute: LoginRoute,
  MyTicketsRoute: MyTicketsRoute,
  RegisterRoute: RegisterRoute,
  ScannerRoute: ScannerRoute,
  WaitlistRoute: WaitlistRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  EventsNewRoute: EventsNewRoute,
  VolunteerTokenRoute: VolunteerTokenRoute,
  EventsIndexRoute: EventsIndexRoute,
  EventsEventIdEditRoute: EventsEventIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
